const COLLECTION_NAME = process.env.NEXT_PUBLIC_VITE_APP_COLLECTION_NAME
const CUSTOMERS_COLLECTION_NAME = process.env.NEXT_PUBLIC_CUSTOMERS_COLLECTION_NAME
const DASHBOARD_COLLECTION_NAME = 'qik_feedback'
const USERS_COLLECTION_NAME = 'businessUsers'
const BUCKET_NAME = 'qik_feedback_test'
const BUCKET_URL = `gs://${COLLECTION_NAME}`
const DSC_SOLUTIONS_ID = 'dsc-solutions'
const ASSETS_FOLDER = {
    icons: 'business/icons',
    background: 'business/background'
}
const LOYALTY_SUBCOLLECTION_NAME = 'loyalty'
const QIK_CUMPLE_SUBCOLLECTION_NAME = 'qik-cumple'
const QIK_REWARDS_SUBCOLLECTION_NAME = 'qik-rewards'
const QIK_STARS_SUBCOLLECTION_NAME = 'qik-stars'
const QIK_STARS_BENEFITS_SUBCOLLECTION_NAME = 'benefits'
const FREE_DINNER_SUBCOLLECTION_NAME = 'free-dinner'
const GIFT_CARD_SUBCOLLECTION_NAME = 'gift-card'
const STORE_SUBCOLLECTION_NAME = 'store'
const ALLIES_SUBCOLLECTION_NAME = 'allies'
const CALCULATOR_SUBCOLLECTION_NAME = 'starts-calculator'

export {
    COLLECTION_NAME,
    CUSTOMERS_COLLECTION_NAME,
    BUCKET_NAME,
    BUCKET_URL,
    ASSETS_FOLDER,
    USERS_COLLECTION_NAME,
    DASHBOARD_COLLECTION_NAME,
    LOYALTY_SUBCOLLECTION_NAME,
    QIK_CUMPLE_SUBCOLLECTION_NAME,
    QIK_REWARDS_SUBCOLLECTION_NAME,
    QIK_STARS_SUBCOLLECTION_NAME,
    QIK_STARS_BENEFITS_SUBCOLLECTION_NAME,
    FREE_DINNER_SUBCOLLECTION_NAME,
    GIFT_CARD_SUBCOLLECTION_NAME,
    STORE_SUBCOLLECTION_NAME,
    ALLIES_SUBCOLLECTION_NAME,
    CALCULATOR_SUBCOLLECTION_NAME,
    DSC_SOLUTIONS_ID
}
