import { generateAutomaticEmail, isAutoGeneratedEmail, extractPhoneFromEmail } from '../emailUtils';

describe('emailUtils', () => {
  describe('generateAutomaticEmail', () => {
    it('should generate email with first and last name', () => {
      const email = generateAutomaticEmail('Juan', 'Pérez', '593991234567');
      expect(email).toBe('juanperez@593991234567.com');
    });

    it('should handle names with accents', () => {
      const email = generateAutomaticEmail('José', 'González', '593991234567');
      expect(email).toBe('josegonzalez@593991234567.com');
    });

    it('should handle names with special characters', () => {
      const email = generateAutomaticEmail('María José', 'García-López', '593991234567');
      expect(email).toBe('mariajosegarciolopez@593991234567.com');
    });

    it('should handle empty names', () => {
      const email = generateAutomaticEmail('', '', '593991234567');
      expect(email).toBe('cliente@593991234567.com');
    });

    it('should clean phone number', () => {
      const email = generateAutomaticEmail('Juan', 'Pérez', '+593 99 123 4567');
      expect(email).toBe('juanperez@593991234567.com');
    });

    it('should handle Colombian phone numbers', () => {
      const email = generateAutomaticEmail('Carlos', 'Rodríguez', '573001234567');
      expect(email).toBe('carlosrodriguez@573001234567.com');
    });
  });

  describe('isAutoGeneratedEmail', () => {
    it('should identify auto-generated emails', () => {
      expect(isAutoGeneratedEmail('juanperez@593991234567.com')).toBe(true);
      expect(isAutoGeneratedEmail('cliente@573001234567.com')).toBe(true);
    });

    it('should reject regular emails', () => {
      expect(isAutoGeneratedEmail('juan@example.com')).toBe(false);
      expect(isAutoGeneratedEmail('user@gmail.com')).toBe(false);
      expect(isAutoGeneratedEmail('test@domain.org')).toBe(false);
    });

    it('should handle case insensitive', () => {
      expect(isAutoGeneratedEmail('JUANPEREZ@593991234567.COM')).toBe(true);
    });
  });

  describe('extractPhoneFromEmail', () => {
    it('should extract phone from auto-generated email', () => {
      const phone = extractPhoneFromEmail('juanperez@593991234567.com');
      expect(phone).toBe('593991234567');
    });

    it('should return null for regular emails', () => {
      const phone = extractPhoneFromEmail('juan@example.com');
      expect(phone).toBe(null);
    });

    it('should handle case insensitive', () => {
      const phone = extractPhoneFromEmail('JUANPEREZ@593991234567.COM');
      expect(phone).toBe('593991234567');
    });
  });
});
